config/routes.rb
Rails.application.routes.draw do

  root to: "restaurants#index"
  resources :reviews
  resources :restaurants do
    resources :reviews
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
  has_many :reviews, :dependent => :destroy

  validates :name, presence: true, uniqueness: true 
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true, inclusion: { within:["AL", "AK", "AS","AZ","AR","CA","CO","CT","DE","DC","FM","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA", 
	"ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
	"NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VI","VA","WA",
	"WV","WI","WY"],
    message: "must be real" }
  validates :zip,  presence: true, format: {with: /\A\d{5}(-\d{4})?\Z/, message: "Incorrect format"}  

 
end

app/models/review.rb
class Review < ActiveRecord::Base
  
  belongs_to :restaurants
  validates :rating, presence: true, :inclusion => {:in => [1,2,3,4,5], message:"1..5 please"}
  validates :restaurant_id, presence: true
  validates :body, presence: true, length: { maximum: 500, message:"Body is too long (max 500 characters)" } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  # GET /restaurants
  def index
    @restaurants = Restaurant.order(id: :DESC)
  end

  # GET /restaurants/1
  def show
    
    @restaurant = Restaurant.find(params[:id])
    
    @review= Review.new
    
    @reviews = Review.where('restaurant_id =?', params[:id])
   
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  def create
  
   
    @restaurant= Restaurant.new(restaurant_params)
  

    if @restaurant.save
      redirect_to new_restaurant_path, notice: 'Restaurant was successfully created.'
    else
      render action: 'new'
    end
  
  end
  
=begin
  def destroy

    @restaurant = Restaurant.find(params[:id]).destroy
    redirect_to @restaurant, notice: 'Restaurant was successfully deleted'
  end  
 

  def edit
  
     @restaurant = Restaurant.find(params[:id])
    
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    
    @restaurant.update(question_params)

  
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render action: 'edit'
    end
  end  
=end  
  

  
  #private

  # Never trust parameters from the scary internet, only allow the white list through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :body, :state, :zip, :city, :address, :category, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # GET /reviews
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  def show
    @review = Review.find(params[:id])
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  # POST /reviews
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to new_restaurant_review_path(@restaurant), notice: 'Review was successfully created.'
    else
      redirect_to new_restaurant_review_path(@restaurant), notice: 'Review was not created.'
    end
  end


  #private

  # Never trust parameters from the scary internet, only allow the white list through.
  def review_params
    params.require(:review).permit(:body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to GoodEats</title>
</head>
<body>
<h1>Welcome to GoodEats!</h1>
	<%@restaurants.each do|rest|%>
	  <br>
	    <%= link_to "Details", restaurant_path(rest.id) %><br>
	   
		Name : <%=rest.name%><br>
		Address : <%=rest.address%><br>
		City : <%=rest.city%><br>
		State : <%=rest.state%><br>
		Zip : <%=rest.zip%><br>
		Category : <%=rest.category%><br>
		Description : <%=rest.description%><br>
    
	<%end%>

</body>
</html>

app/views/restaurants/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enter your question</title>
</head>
<body>
<h1>Join the Foodeverse</h1><br>

<%= form_for @restaurant, action: "create", html: {class: "nifty_form"} do |f| %>
  <div>
    <% if flash.any? %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <%end%> 
  </div> 
  
  <% if @restaurant.errors.any? %>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <%end%>

  <%= f.label :name, "Name" %><br />
  <p><%= f.text_field :name %></p><br>
  <%= f.label :address, "Address" %><br />
  <%= f.text_field :address%><br>
  <%= f.label :city, "City" %><br />
  <p><%= f.text_field :city %></p><br>
  <%= f.label :state, "State" %><br />
  <p><%= f.text_field :state %></p><br>
   <%= f.label :zip, "Zip" %><br />
  <p><%= f.text_field :zip %></p><br>
  <%= f.label :description, "Description" %><br />
  <p><%= f.text_field :description %></p><br>

  <%= f.label :category, "Category" %><br />
  <p><%= f.text_field :category %></p><br>
  <%= f.submit "Create" %>

<% end %>
<br>
<%= link_to "View all restaurants ", restaurants_path %>


</body>
</html>

app/views/restaurants/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant Details</title>
</head>
<body>
	

  <% if flash.any? %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
  <% end %>


  <% if @restaurant.errors.any? %>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <%end%><br>
  <%= link_to "Home", restaurants_path%><br> 
  <h1><%=@restaurant.name%></h1>

  <li>Name : <%=@restaurant.address%></li><br>
  <li>City : <%=@restaurant.city%><br></li>
  <li>State : <%=@restaurant.state%></li><br>
  <li>Zip : <%=@restaurant.zip%></li><br>
  <li>Category : <%=@restaurant.category%></li><br>
  <li>Description : <%=@restaurant.description%></li><br>
  <br>
   
   
  <br>
  <h3>See all reviews</h3>
    <%@restaurant.reviews.each do|rev|%>
       Rating : <%=rev.rating%><br>
       Body : <%=rev.body%><br>
       Created at : <%=rev.created_at%><br>
    <%end%>
	 <br>
     	
  <%= link_to "Create a new review ", new_restaurant_review_path(@restaurant) %>
  <br><br>

  <h3>Feeling lazy?</h3>

  <%= form_for ([@restautant, @review]) do |f| %>
    <div>
      <% if flash.any? %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <%end%> 
    </div> 
  
    <% if @review.errors.any? %>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <%end%>

    <%= f.label :rating, "Rating" %><br />
    <p><%= f.text_field :rating %></p><br>
    <%= f.label :body, "Body" %><br />
    <%= f.text_area :body%><br>
    <%= f.submit "Create" %>

  <% end %>
		
</body>
</html>

app/views/reviews/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enter your question</title>
</head>
<body>
<h1>Lay down your feelings</h1><br>

<%= form_for ([@restaurant, @review]) do |f| %>
  <div>
    <% if flash.any? %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <%end%> 
  </div> 
  
  <% if @review.errors.any? %>
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <%end%>

  <%= f.label :rating, "Rating" %><br />
  <p><%= f.text_field :rating %></p><br>
  <%= f.label :body, "Body" %><br>
  <%= f.text_area :body%><br>
  <%= f.submit "Create" %><br><br>
  <%= link_to "Back to restaurant", restaurant_path(@restaurant) %>
<% end %>

</body>
</html>